"""created by column add

Revision ID: 31173886c62a
Revises: b4a9507db1d0
Create Date: 2022-10-15 06:46:09.482353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31173886c62a'
down_revision = 'b4a9507db1d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_id', table_name='task')
    op.drop_index('ix_task_status', table_name='task')
    op.drop_index('ix_task_text', table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='task_pkey')
    )
    op.create_index('ix_task_text', 'task', ['text'], unique=False)
    op.create_index('ix_task_status', 'task', ['status'], unique=False)
    op.create_index('ix_task_id', 'task', ['id'], unique=False)
    # ### end Alembic commands ###
