"""task create

Revision ID: 9db57ca280f6
Revises: 6ef7561adc13
Create Date: 2022-10-12 00:27:28.590334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9db57ca280f6'
down_revision = '6ef7561adc13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
