"""task update status

Revision ID: b4a9507db1d0
Revises: 634f20ac942c
Create Date: 2022-10-13 17:57:41.457902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a9507db1d0'
down_revision = '634f20ac942c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_column('task', 'status')
    # ### end Alembic commands ###
